export interface ExportMessage {
	role: 'user' | 'assistant';
	content: string;
	sources?: {
		pmid: string;
		title: string;
		authors: string | null;
		year: number | null;
		pubmedUrl: string;
	}[] | null;
}

export async function exportToPDF(
	messages: ExportMessage[],
	mode: 'nutrition' | 'research',
) {
	const disclaimer =
		mode === 'nutrition'
			? '⚕️ This is a research summary, not medical advice. Consult a healthcare provider for personal recommendations.'
			: '🔬 This is a research summary, not clinical guidance. Consult relevant specialists for clinical decisions.';

	const brandLabel =
		mode === 'nutrition' ? 'Healthwise Nutrition' : 'Healthwise Research';

	const title =
		messages.find((m) => m.role === 'user')?.content.slice(0, 80) ??
		'Conversation';

	const date = new Date().toLocaleDateString('en-US', {
		year: 'numeric',
		month: 'long',
		day: 'numeric',
	});

	let html = `
		<div style="font-family: Georgia, serif; max-width: 700px; margin: 0 auto; padding: 40px 20px; color: #1e293b;">
			<div style="border-bottom: 2px solid #1e3a5f; padding-bottom: 16px; margin-bottom: 32px;">
				<h1 style="font-size: 22px; margin: 0 0 4px;">${escapeHtml(title)}</h1>
				<p style="font-size: 12px; color: #64748b; margin: 0;">${brandLabel} · Exported ${date}</p>
			</div>
	`;

	for (const msg of messages) {
		if (msg.role === 'user') {
			html += `
				<div style="margin-bottom: 24px;">
					<p style="font-size: 11px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin: 0 0 4px;">Question</p>
					<p style="font-size: 14px; margin: 0;">${escapeHtml(msg.content)}</p>
				</div>
			`;
		} else {
			html += `
				<div style="margin-bottom: 32px;">
					<p style="font-size: 11px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin: 0 0 8px;">Answer</p>
					<div style="font-size: 13px; line-height: 1.7;">${formatContent(msg.content, msg.sources)}</div>
			`;

			if (msg.sources && msg.sources.length > 0) {
				html += `
					<div style="margin-top: 16px; padding-top: 12px; border-top: 1px solid #e2e8f0;">
						<p style="font-size: 11px; font-weight: 600; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; margin: 0 0 8px;">Sources</p>
				`;
				msg.sources.forEach((s, i) => {
					const firstAuthor = s.authors
						? s.authors.split(',')[0] +
							(s.authors.includes(',') ? ' et al.' : '')
						: '';
					html += `
						<p style="font-size: 11px; color: #475569; margin: 0 0 6px;">
							[${i + 1}] ${escapeHtml(s.title)}${firstAuthor ? ' — ' + escapeHtml(firstAuthor) : ''}${s.year ? ' (' + s.year + ')' : ''}<br/>
							<a href="${s.pubmedUrl}" style="color: #2563eb; text-decoration: none; font-size: 10px;">${s.pubmedUrl}</a>
						</p>
					`;
				});
				html += `</div>`;
			}

			html += `</div>`;
		}
	}

	html += `
		<div style="border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 32px;">
			<p style="font-size: 10px; color: #94a3b8; margin: 0;">${disclaimer}</p>
			<p style="font-size: 10px; color: #94a3b8; margin: 4px 0 0;">Generated by ${brandLabel} · healthwise.ai</p>
		</div>
	</div>
	`;

	const filename = `${title.replace(/[^a-zA-Z0-9 ]/g, '').trim().slice(0, 50)}.pdf`;

	const html2pdf = (await import('html2pdf.js')).default;

	await html2pdf()
		.set({
			margin: [10, 10, 10, 10],
			filename,
			image: { type: 'jpeg', quality: 0.98 },
			html2canvas: {
				scale: 2,
				onclone: (doc: Document) => {
					doc.querySelectorAll('link[rel="stylesheet"], style').forEach(
						(el) => el.remove(),
					);
				},
			},
			jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
		})
		.from(html)
		.save();
}

function escapeHtml(text: string): string {
	return text
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}

function formatContent(
	text: string,
	sources?: ExportMessage['sources'],
): string {
	return text
		.split('\n')
		.filter(
			(line) =>
				!line.trim().startsWith('→') &&
				line.trim() !== '**Related Nutrition Topics**' &&
				line.trim() !== '**Related Research Directions**',
		)
		.map((line) => {
			if (!line.trim()) return '<br/>';

			const heading = line.match(/^\*{1,2}([^*]+)\*{1,2}$/);
			if (heading)
				return `<p style="font-weight: 600; margin: 16px 0 4px;">${escapeHtml(heading[1])}</p>`;

			let formatted = escapeHtml(line).replace(
				/\*\*([^*]+)\*\*/g,
				'<strong>$1</strong>',
			);

			formatted = formatted.replace(/\[PMID:\s*(\d+)\]/g, (_, pmid) => {
				const idx = sources?.findIndex((s) => s.pmid === pmid) ?? -1;
				const label = idx >= 0 ? idx + 1 : pmid;
				return `<sup style="color: #2563eb; font-size: 9px;">[${label}]</sup>`;
			});

			return `<p style="margin: 0 0 8px;">${formatted}</p>`;
		})
		.join('');
}
